server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5539/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

address:
  country: testCountry
  city: testCity
  street: testStreet
  house: testHouse
  flat: testFlat