spring:
  application:
    name: payment
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      retry:
        use-random-policy: true
        max-attempts: 6000